### ISSUE TITLE
API response when private key is not in posession

### ISSUE THREAD

**Issue by vivekagr** [pwnedkeys/pwnedkeys-site#1]
The API documentation isn't clear about the case where the public key appears in pwnedkeys.com's database, but the private key is not present because only a signed attestation was submitted for it.  This means that JWS cannot be returned since pwnedkeys isn't in possession of the private key.

Will the API still respond with status code 200?

**Comment by mpalmer** [comment]
The API will return a 200, with a JWS produced by the compromised key, because the attestation that is submitted *is* that signed JWS.  I agree that the documentation doesn't make that particularly clear, as it talks about "private key is in the database" rather than a more accurate description of the state of the key, which would be more along the lines of "has been attested to be compromised".  I'll do some tidying up there to make it clearer.

**Comment by vivekagr** [comment]
That makes sense, thank you! 👍
